---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: crd-validation-webhook
webhooks:
  - name: "webhook.crdvalidator.io"
    rules:
    - apiGroups: ["apiextensions.k8s.io"]
      apiVersions: ["v1"]
      operations: ["CREATE", "UPDATE"]
      resources: ["customresourcedefinitions"]
      scope: "*"
    clientConfig:
      service:
        namespace: crdvalidator-system
        name: crd-validation-webhook
        path: /validate-crd
        port: 9443
    objectSelector:
      matchLabels:
        core.rukpak.io/owner-kind: BundleDeployment
    admissionReviewVersions: ["v1"]
    sideEffects: None
