---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helm-provisioner
  namespace: rukpak-system
spec:
  secretName: helm-provisioner-cert
  dnsNames:
    - $(HELM_PROVISIONER_SERVICE_NAME).$(HELM_PROVISIONER_SERVICE_NAMESPACE).svc
    - $(HELM_PROVISIONER_SERVICE_NAME).$(HELM_PROVISIONER_SERVICE_NAMESPACE).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: rukpak-ca-issuer
